### ISSUE TITLE
Q. Java에서 public, private, protected 접근자의 차이점은?

### ISSUE THREAD

**Issue by luckjjh** [1004mapa2/JavaSpace#1]
제곧내

**Comment by 1004mapa2** [comment]
public은 열린 문private는 같은 클protected는 뭐시기+자손디폴트는 어디갔냐나의 iPhone에서 보냄2023. 1. 4. 오전 11:35, JungHyeon Jung ***@***.***> 작성:﻿
제곧내

**Comment by luckjjh** [comment]
3개 국룰인줄 ㅋㅋ

**Comment by 1004mapa2** [comment]
ㅋㅋ 뭔 이런 기능도 있네
