### ISSUE TITLE
Q. 코딩 문제

### ISSUE THREAD

**Issue by luckjjh** [1004mapa2/JavaSpace#5]
학점이 A, B이면 "Excellent", 학점이 C, D이면 "Good", 학점이 F이면 "Bye"라고 출력하는 프로그램을 작성하시오.

입출력 예시)

입력
B
출력
Excellent

코드 작성하고, PR 생성까지 ㄱㄱ 모르면 검색 ㄱ

**Comment by 1004mapa2** [comment]
하긴 했는데 맞는지 모르겠음 ㅋㅋ

**Comment by luckjjh** [comment]
좀 있다가 예시로 보여줌
