### ISSUE TITLE
Q. overriding과 overloading의 차이점은?

### ISSUE THREAD

**Issue by luckjjh** [1004mapa2/JavaSpace#7]
ㅈㄱㄴ

**Comment by 1004mapa2** [comment]
over 타기, over 로딩 중 ㅋ.ㅋ

**Comment by 1004mapa2** [comment]
overloading : 한 클래스에 같은 이름 메서드 정의
overriding : 조상 클래스에서 상속 받은 메서드 내용에 + 추가해서 변경
