### ISSUE TITLE
Q. 추상 클래스와 인터페이스를 설명하고, 차이에 대해 설명하시오.

### ISSUE THREAD

**Issue by luckjjh** [1004mapa2/JavaSpace#8]
ㅈㄱㄴ

**Comment by 1004mapa2** [comment]
추상 클래스 : 미완성 메서드(추상 클래스)를 갖고 있는 클래스. 상속을 통해 추상 메서드를 완성해야 인스턴스 생성가능

인터페이스 : 추상 메서드의 집합, 구현된 것이 전혀 없는 설계도. 항상 public abstract, 상수는 public static final, 다중 상속이 가능

차이점 - 추상 클래스는 iv(인스턴스 변수), 생성자, 추상 메서드를 가지고 있지만 인터페이스는 추상 메서드와 상수밖에 없다.
