### ISSUE TITLE
절대 git config를 수정하지마

### ISSUE THREAD

**Issue by luckjjh** [1004mapa2/JavaSpace#9]
**절대** git config에 user.name, user.email을 수정하지마
https://webisfree.com/2018-07-26/git-config-%EC%84%A4%EC%A0%95-%ED%99%95%EC%9D%B8-%EB%B0%8F-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0

**Comment by 1004mapa2** [comment]
절대 수정 했다고 하지마
